---
title: "데이터 다운로드"

toc: true
toc-location: left
toc-title: "데이터 목차 ..."
toc-depth: 5
toc-expand: true

resources: 
    - bookdata/lifexp5.csv
    - bookdata/lifexp5L.csv
    - bookdata/LifeTbl.csv
---

**wintree의 데이터 리포지토리**

### R 기초 및 활용

#### 데이터 변환

##### 기대수명(출생시 기대여명) 전체, 남, 여 (2020년 ~ 2024년)
- 출처: KOSIS 인구동태건수 및 동태율 추이(출생,사망,혼인,이혼) 년, 1970~1925p (자료갱신 2026-03-19): DT_1B8000F
- [열 배열(wide shape) lifexp5.csv 다운로드](bookdata/lifexp5.csv){download=""}
- [행 배열(long shape) lifexp5L.csv 다운로드](bookdata/lifexp5L.csv){download=""}

```{r}
#| echo: false
#| output: false
list_of_packages <- c("readr", "tidyr")
for (p in list_of_packages) {
    if (!requireNamespace(p, quietly = TRUE)) {
        install.packages(p, dependencies = TRUE, verbose = FALSE)
    }
    library(p, character.only = TRUE, verbose = FALSE)
}
tb_w <- read_csv("data/LEB_utf8.csv", col_select = c(기대수명, `2024`:`2020`), locale = locale(encoding = "UTF-8"), show_col_types = FALSE)
write.csv(tb_w, file = "bookdata/lifexp5.csv", fileEncoding = "UTF-8")
tb_l <- pivot_longer(tb_w, cols = `2024`:`2020`, names_to = "시점", values_to = "년")
write.csv(tb_l, file = "bookdata/lifexp5L.csv", fileEncoding = "UTF-8")
rm(list = ls())
```

##### 완전생명표 2024년, 1970년
- 출처: KOSIS 완전생명표(1세별) 년, 1970~2024 (자료갱신 2025-12-03): DT_1B42
- [LifeTbl.csv 다운로드](bookdata/LifeTbl.csv){download=""}

```{r}
#| echo: false
#| output: false
list_of_packages <- c("readxl", "tidyr", "dplyr", "janitor", "tibble")
for (p in list_of_packages) {
    if (!requireNamespace(p, quietly = TRUE)) {
        install.packages(p, dependencies = TRUE, verbose = FALSE)
    }
    library(p, character.only = TRUE, verbose = FALSE)
}
tb_1970 <- read_excel("kosis/DT_1B42.xlsx", sheet = "1970", col_types = c("text", rep("numeric", 18)), skip = 1) |> add_column(시점 = "1970", .before = 1)
tb_2024 <- read_excel("kosis/DT_1B42.xlsx", sheet = "2021_2024") |>
    select(연령별, starts_with("2024...")) |> row_to_names(row_number = 1) |> mutate(across(2:19, as.numeric)) |> add_column(시점 = "2024", .before = 1)
tb_life <- bind_rows(tb_2024, tb_1970)
write.csv(tb_life, file = "bookdata/LifeTbl.csv", fileEncoding = "UTF-8")
rm(list = ls())
```

